# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Stip"
license = "MIT"
licenselink = "https://github.com/EmielH/stip-hugo/blob/master/LICENSE"
description = "Stip is a single-page Hugo theme to introduce yourself."
homepage = "https://github.com/EmielH/stip-hugo"
tags =  ["minimal", "clean", "responsive", "simple", "personal", "starter", "single page", "onepage", "Font Awesome", "landing page"]
features = []
min_version = "0.50"

[author]
  name = "Emiel Hollander"
  homepage = "https://www.emielhollander.nl"
