baseURL = "https://www.loganayliffe.com"
theme = "hello-friend-ng"
title = "Logan Ayliffe"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params.logo]
  logoText     = "hi there, friend"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  subtitle = "i do stuff with computers"
  homeSubTitle = "social justice-minded tech nerd and CS graduate student @ University of Pennsylvania."
  
  # Metadata mostly used in document's head
  description = "Homepage and contact info for Logan Ayliffe"
  keywords = "homepage, blog, science, coding, development, programming, tech, technology"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/logan_ayliffe"

  [[params.social]]
    name = "email"
    url  = "mailto:logan.life.online@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/logan-life"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/logan-ayliffe"

  [[params.social]]
    name = "goodreads"
    url  = "https://www.goodreads.com/logan_ayliffe"
    

